version: '3.9'

services:
  dev-portfolio-tracker:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file:
      - ../.envs/.dev
    image:
      dev-portfolio-tracker
    container_name:
      dev-portfolio-tracker
    ports:
      - "6010:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev_agent
    volumes:
      - ../:/usr/src/app
    restart: always
    command: bash -c 'uvicorn main:app --proxy-headers --host 0.0.0.0'
    depends_on:
      - postgres-agent
    hostname: dev-portfolio-tracker


networks:
  dev_agent: { }